import type { Role } from "../types";

export const roles: Role[] = [
  {
    id: "guardian-grimorio",
    name: "Guardián del Grimorio",
    description: "Crea reglas temporales para todos.",
    power: "Puede crear una regla absurda del Grimorio.",
    costOrLimit: "Quien rompa su regla gana +1 Locura.",
  },
  {
    id: "rompe-reglas",
    name: "Rompe-Reglas",
    description: "Elimina reglas activas.",
    power: "Puede eliminar una regla del Grimorio.",
    costOrLimit: "Gana +1 Locura.",
    phrase: "¡El Grimorio arde!",
  },
  {
    id: "censor-culto",
    name: "Censor del Culto",
    description: "Prohíbe palabras comunes.",
    power: "Declara una palabra prohibida.",
    costOrLimit: "Quien diga la palabra gana +1 Locura.",
  },
  {
    id: "traductor-profano",
    name: "Traductor Profano",
    description: "Obliga a una persona a hablar de forma rara.",
    power: "Elige a alguien para hablar como villano, narrador, vendedor, NPC o profeta.",
    costOrLimit: "Si se olvida, gana +1 Locura.",
  },
  {
    id: "fiscal-herejia",
    name: "Fiscal de la Herejía",
    description: "Acusa dramáticamente cuando alguien rompe una regla.",
    power: "Puede acusar a alguien con una frase teatral.",
    costOrLimit: "Si el grupo acepta: acusado +1. Si fue forzado: Fiscal +1.",
  },
  {
    id: "bufon-abismo",
    name: "Bufón del Abismo",
    description: "Cambia una penalización por reto.",
    power: "Cuando alguien va a ganar +1 Locura, puede ofrecer un reto alternativo.",
    costOrLimit: "Si falla o rechaza, gana +1 Locura.",
  },
  {
    id: "portador-reliquia",
    name: "Portador de la Reliquia",
    description: "Tiene un objeto físico que bloquea una penalización.",
    power: "Puede bloquear una penalización de +1 Locura.",
    costOrLimit: "Después de usarlo, debe pasar la reliquia a otra persona.",
  },
  {
    id: "copista-maldito",
    name: "Copista Maldito",
    description: "Convierte una regla general en una regla personal.",
    power: "Copia una regla activa y se la aplica a una persona.",
    costOrLimit: "Si esa persona la rompe, gana +1 Locura.",
  },
  {
    id: "deudor-culto",
    name: "Deudor del Culto",
    description: "Puede salvarse ahora, pero paga peor después.",
    power: "Puede decir “Le debo una al culto” y evitar +1 Locura.",
    costOrLimit: "La próxima falla suma +1 y activa Tributo Ritual si corresponde.",
  },
  {
    id: "confesor-culto",
    name: "Confesor del Culto",
    description: "Cura Locura de otros absorbiéndola.",
    power: "Elige a alguien para una confesión falsa o dramática aceptada por el grupo.",
    costOrLimit: "Esa persona pierde -1 Locura y el Confesor gana +1. No se cura a sí mismo.",
    phrase: "Confiesa ante el culto.",
  },
  {
    id: "elegido-cthulhu",
    name: "Elegido de Cthulhu",
    description: "Se ofrece como canal del abismo para empujar al grupo al caos.",
    power: "Durante un Chequeo puede hacer un Tributo Mayor y arrastrar a 3 jugadores a +1 Locura.",
    costOrLimit: "Quiere que al final gane Invocar.",
    phrase: "Yo bebo por el abismo.",
  },
];
